export const FETCH_CONTENT_PENDING = 'FETCH_CONTENT_PENDING';
export const FETCH_CONTENT_SUCCESS = 'FETCH_CONTENT_SUCCESS';
export const FETCH_CONTENT_ERROR = 'FETCH_CONTENT_ERROR';

export const ACTION_CONTENT_SET = 'ACTION_CONTENT_SET';
export const ACTION_CONTENT_SET_CURRENT = 'ACTION_CONTENT_SET_CURRENT';

export const ACTION_LOCAL_CONTENT_SET = 'ACTION_LOCAL_CONTENT_SET';
export const ACTION_LOCAL_CONTENT_SET_CURRENT = 'ACTION_LOCAL_CONTENT_SET_CURRENT';
