export const ACTION_PLAYER_SET = 'ACTION_PLAYER_SET';
export const ACTION_INIT_PLAYER = 'ACTION_INIT_PLAYER';
export const ACTION_PLAYHUB_PLAYER_SET = 'ACTION_PLAYHUB_PLAYER_SET';
export const ACTION_PLAYHUB_INIT_PLAYER = 'ACTION_PLAYHUB_INIT_PLAYER';
